import mods.jei.JEI.removeAndHide;

import mods.jei.JEI;

import crafttweaker.item.IItemStack;

var itemsToRemove = [

<ic2:itemdynamites>,
<ic2:itemdynamites:1>,
<ic2c_extras:copperplate>,
<ic2c_extras:tinplate>,
<ic2c_extras:silverplate>,
<ic2c_extras:leadplate>,
<ic2c_extras:ironplate>,
<ic2c_extras:goldplate>,
<ic2c_extras:refinedironplate>,
<ic2c_extras:steelplate>,
<ic2c_extras:bronzeplate>,
<ic2c_extras:plasmacutter>,
<ic2c_extras:gearingpress>,
<ic2c_extras:lathingpress>,
<ic2c_extras:cuttingpress>,
<ic2c_extras:extrudingpress>,
<ic2c_extras:rollingpress>,
<ic2c_extras:blankpress>,
<ic2c_extras:slag>,
<ic2c_extras:leaddust>,
<ic2c_extras:leadingot>,
<ic2c_extras:coppercrushedore>,
<ic2c_extras:copperpurifiedcrushedore>,
<ic2c_extras:coppertinydust>,
<ic2c_extras:coppersmalldust>,
<ic2c_extras:leadblock>,
<ic2c_extras:leadcrushedore>,
<ic2c_extras:leadpurifiedcrushedore>,
<ic2c_extras:leadtinydust>,
<ic2c_extras:leadsmalldust>,
<ic2c_extras:silversmalldust>,
<ic2c_extras:silvertinydust>,
<ic2c_extras:silvercrushedore>,
<ic2c_extras:silverpurifiedcrushedore>,
<ic2c_extras:tintinydust>,
<ic2c_extras:tinsmalldust>,
<ic2c_extras:tinpurifiedcrushedore>,
<ic2c_extras:tincrushedore>,

<ic2:blockmachinehv:5>,
<ic2c_extras:cutter>,

<ic2c_extras:uraniumdust>,
<ic2c_extras:uraniumpurifiedcrushedore>,
<ic2c_extras:uraniumcrushedore>,

<ic2c_extras:aluminumtinydust>,
<ic2c_extras:aluminumpurifiedcrushedore>,
<ic2c_extras:aluminumcrushedore>,

<ic2c_extras:platinumcrushedore>,
<ic2c_extras:platinumpurifiedcrushedore>,
<ic2c_extras:platinumtinydust>,

<ic2c_extras:nickeltinydust>,
<ic2c_extras:nickelcrushedore>,
<ic2c_extras:nickelpurifiedcrushedore>,

<ic2c_extras:goldsmalldust>,
<ic2c_extras:goldtinydust>,
<ic2c_extras:goldpurifiedcrushedore>,
<ic2c_extras:goldcrushedore>,

<ic2c_extras:ironcrushedore>,
<ic2c_extras:ironpurifiedcrushedore>,

<ic2c_extras:diamonddust>,

<ic2c_extras:bronzesmalldust>,
<ic2c_extras:bronzetinydust>,
<gtclassic:bronze_dustsmall>,

<ic2c_extras:obsidiansmalldust>,
<ic2c_extras:obsidiantinydust>,
<gtclassic:obsidian_dustsmall>,

<ic2c_extras:ironsmalldust>,
<ic2c_extras:irontinydust>,

<gtclassic:saltpeter_dustsmall>,
<gtclassic:slag_dustsmall>,
<gtclassic:batteryalloy_dustsmall>,
<gtclassic:tungsten_dustsmall>,
<gtclassic:redalloy_dustsmall>,
<gtclassic:carbon_dustsmall>,
<gtclassic:invar_dustsmall>,
<gtclassic:chromite_dustsmall>,
<gtclassic:grossular_dustsmall>,
<gtclassic:almandine_dustsmall>,
<gtclassic:calcite_dustsmall>,
<gtclassic:galena_dustsmall>,
<gtclassic:pyrite_dustsmall>,
<gtclassic:lithium_dustsmall>,
<gtclassic:endstone_dustsmall>,
<gtclassic:phosphorus_dustsmall>,
<gtclassic:brass_dustsmall>,
<gtclassic:plutonium_dustsmall>,
<gtclassic:clay_dustsmall>,
<gtclassic:andradite_dustsmall>,
<gtclassic:electrum_dustsmall>,
<gtclassic:bauxite_dustsmall>,
<gtclassic:constantan_dustsmall>,
<gtclassic:enderpearl_dustsmall>,
<gtclassic:kanthal_dustsmall>,
<gtclassic:osmiridium_dustsmall>,
<gtclassic:charcoal_dustsmall>,
<gtclassic:uvarovite_dustsmall>,
<gtclassic:magnesium_dustsmall>,
<gtclassic:gunpowder_dustsmall>,
<gtclassic:sodalite_dustsmall>,
<gtclassic:steel_dustsmall>,
<gtclassic:endereye_dustsmall>,
<gtclassic:technetium_dustsmall>,
<gtclassic:lazurite_dustsmall>,
<gtclassic:magnalium_dustsmall>,
<gtclassic:marble_dustsmall>,
<gtclassic:flint_dustsmall>,
<gtclassic:coal_dustsmall>,
<gtclassic:uranium_dustsmall>,
<gtclassic:stainlesssteel_dustsmall>,
<gtclassic:tungstensteel_dustsmall>,
<gtclassic:sphalerite_dustsmall>,
<gtclassic:cassiterite_dustsmall>,
<gtclassic:cinnabar_dustsmall>,
<gtclassic:iridium_dustsmall>,
<gtclassic:spessartine_dustsmall>,
<gtclassic:basalt_dustsmall>,
<gtclassic:redrock_dustsmall>,
<gtclassic:coke_dustsmall>,
<gtclassic:ruby_dustsmall>,
<gtclassic:silicondioxide_dustsmall>,
<gtclassic:stone_dustsmall>,
<gtclassic:silicon_dustsmall>,
<gtclassic:granite_dustsmall>,
<gtclassic:nichrome_dustsmall>,

<gtclassic:nichrome_stick>,
<gtclassic:osmium_stick>,
<gtclassic:nickel_stick>,
<gtclassic:brass_stick>,
<gtclassic:chrome_stick>,
<gtclassic:tin_stick>,
<gtclassic:platinum_stick>,
<gtclassic:osmiridium_stick>,
<gtclassic:lead_stick>,
<gtclassic:constantan_stick>,
<gtclassic:antimony_stick>,
<gtclassic:electrum_stick>,
<gtclassic:gold_stick>,
<gtclassic:magnalium_stick>,
<gtclassic:technetium_stick>,
<gtclassic:silver_stick>,
<gtclassic:zinc_stick>,
<gtclassic:invar_stick>,
<gtclassic:redalloy_stick>,
<gtclassic:tungsten_stick>,
<gtclassic:osmium_gear>,
<gtclassic:nickel_gear>,
<gtclassic:iridium_gear>,
<gtclassic:refinediron_gear>,
<gtclassic:brass_gear>,
<gtclassic:chrome_gear>,
<gtclassic:platinum_gear>,
<gtclassic:aluminium_gear>,
<gtclassic:osmiridium_gear>,
<gtclassic:lead_gear>,
<gtclassic:antimony_gear>,
<gtclassic:electrum_gear>,
<gtclassic:technetium_gear>,
<gtclassic:silver_gear>,
<gtclassic:zinc_gear>,
<gtclassic:invar_gear>,
<gtclassic:tungsten_gear>,
<gtclassic:nichrome_plate>,
<gtclassic:plutonium_plate>,
<gtclassic:kanthal_plate>,
<gtclassic:constantan_plate>,
<gtclassic:antimony_plate>,
<gtclassic:manganese_plate>,
<gtclassic:nichrome_nugget>,
<gtclassic:silicon_nugget>,
<gtclassic:osmium_nugget>,
<gtclassic:nickel_nugget>,
<gtclassic:iridium_nugget>,
<gtclassic:titanium_nugget>,
<gtclassic:tungstensteel_nugget>,
<gtclassic:stainlesssteel_nugget>,
<gtclassic:plutonium_nugget>,
<gtclassic:brass_nugget>,
<gtclassic:chrome_nugget>,
<gtclassic:platinum_nugget>,
<gtclassic:aluminium_nugget>,
<gtclassic:osmiridium_nugget>,
<gtclassic:kanthal_nugget>,
<gtclassic:lead_nugget>,
<gtclassic:constantan_nugget>,
<gtclassic:antimony_nugget>,
<gtclassic:electrum_nugget>,
<gtclassic:magnalium_nugget>,
<gtclassic:manganese_nugget>,
<gtclassic:technetium_nugget>,
<gtclassic:steel_nugget>,
<gtclassic:silver_nugget>,
<gtclassic:bronze_nugget>,
<gtclassic:zinc_nugget>,
<gtclassic:invar_nugget>,
<gtclassic:thorium_nugget>,
<gtclassic:redalloy_nugget>,
<gtclassic:tungsten_nugget>,
<gtclassic:batteryalloy_nugget>,

<gtc_expansion:small_bronze_pipe>,
<gtc_expansion:bronze_pipe>,
<gtc_expansion:large_bronze_pipe>,
<gtc_expansion:huge_bronze_pipe>,
<gtc_expansion:quad_bronze_pipe>,
<gtc_expansion:small_steel_pipe>,
<gtc_expansion:steel_pipe>,
<gtc_expansion:large_steel_pipe>,
<gtc_expansion:huge_steel_pipe>,
<gtc_expansion:quad_steel_pipe>,
<gtc_expansion:small_invar_pipe>,
<gtc_expansion:invar_pipe>,
<gtc_expansion:large_invar_pipe>,
<gtc_expansion:huge_invar_pipe>,
<gtc_expansion:quad_invar_pipe>,
<gtc_expansion:small_stainlesssteel_pipe>,
<gtc_expansion:stainlesssteel_pipe>,
<gtc_expansion:large_stainlesssteel_pipe>,
<gtc_expansion:quad_stainlesssteel_pipe>,
<gtc_expansion:small_tungstensteel_pipe>,
<gtc_expansion:tungstensteel_pipe>,
<gtc_expansion:large_tungstensteel_pipe>,
<gtc_expansion:huge_tungstensteel_pipe>,
<gtc_expansion:quad_tungstensteel_pipe>,
<gtc_expansion:brass_pipe>,
<gtc_expansion:large_brass_pipe>,

<ic2c_extras:steelingot>,
<ic2c_extras:steelblock>,
<ic2:blockmachinelv:15>,

<gtclassic:flintmortar>,
<gtclassic:ironmortar>

] as IItemStack[];

for stuffToRemove in itemsToRemove{

    removeAndHide(stuffToRemove);
    recipes.remove(stuffToRemove);

}
